[package]
name = "forbruk"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
ron = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
